name: Steve Drury
favicon: null
layout_spectrum: 0.9779526733327657
typography_spectrum: 0.3236778536811471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6842384489718825
  lightness: 0.10943951294757426
  saturation: 0.9154531210660934
  rhythmicContrast: 0.06754122162237763
purpose: []
