name: Steve Drury
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffa93a'
    - '#8f2d00'
    - '#b17428'
    - '#fdf9a9'
  brandStrength: 0.6875
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
